In [ ]:
# Step 1: Check for Non-Zero Rows
# Traverse through first column of the matrix to search for non-zero entries. 
# Below is the function in which we are checking for non-zero rows.


def find_nonzero_row(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    for row in range(pivot_row, nrows):
        if matrix[row, col] != 0:
            return row
    return None
    
#Step 2: Swap Rows
# After finding a non-zero entry, bring non-zero row to the top of the matrix so that we can achieve our first step towards
# row echelon form(by swapping rows). Below is the code part that we will use in our main code for swapping the rows. 
# In this case, our non-zero row is the first row so it will be swapped by itself

def swap_rows(matrix, row1, row2):
	matrix[[row1, row2]] = matrix[[row2, row1]]

# Step 3: Make Pivot Element of Pivot Row “1”
# It is not compulsory to make the pivot element(First non-zero entry from the left) 1 but we will make it 1 
# for convenience. This is done by floor dividing the pivot row(In this case, first row) by pivot element(which is 2). 
# After dividing row will become [2//2=1 , 3//2=1]

def make_pivot_one(matrix, pivot_row, col):
    pivot_element = matrix[pivot_row, col]
    matrix[pivot_row] //= pivot_element
    
# Step 4: Eliminate Elements Below Pivots to get Row Echelon Form
# Last step is to eliminate all the entries below the pivot element(making them zero). 
# This is done by multiplying the element below pivot element with pivot row(which is in this case, first row) and 
# then subtracting it from second row

def eliminate_below(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    pivot_element = matrix[pivot_row, col]
    for row in range(pivot_row + 1, nrows):
        factor = matrix[row, col]
        matrix[row] -= factor * matrix[pivot_row]
        
# Step 5: Implement All Functions Above
def row_echelon_form(matrix):
    nrows = matrix.shape[0]
    ncols = matrix.shape[1]
    pivot_row = 0
# this will run for number of column times. If matrix has 3 columns this loop will run for 3 times
    for col in range(ncols):
        nonzero_row = find_nonzero_row(matrix, pivot_row, col)
        if nonzero_row is not None:
            swap_rows(matrix, pivot_row, nonzero_row)
            make_pivot_one(matrix, pivot_row, col)
            eliminate_below(matrix, pivot_row, col)
            pivot_row += 1
    return matrix

In [40]:
#REF

import numpy as np
# Function to check if matrix is in REF
 
def findnonzerorow(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    for row in range(pivot_row, nrows):
        if matrix[row, col] != 0:
            return row
    return None
 
# Swapping rows so that we can have our non zero row on the top of the matrix
def interchangerows(matrix, row1, row2):
    matrix[[row1, row2]] = matrix[[row2, row1]]
 

def reducerows(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    pivot_element = matrix[pivot_row, col]
    for row in range(pivot_row + 1, nrows):
        factor = matrix[row, col]
        matrix[row] -= factor * (matrix[pivot_row]//pivot_element)

# Implementing above functions
def getrowechelonform(matrix):
    nrows = matrix.shape[0]
    ncols = matrix.shape[1]
    pivot_row = 0

    for col in range(ncols):
        nonzero_row = findnonzerorow(matrix, pivot_row, col)        
        if nonzero_row is not None:
            interchangerows(matrix, pivot_row, nonzero_row)     
            reducerows(matrix, pivot_row, col)
            pivot_row += 1
    return matrix

matrix = np.array([[0,-2,4,-2],[2,1,10,7],[-4,4,-8,4],[4,-1,14,6]])
print("Matrix Before Converting:")
print(matrix)
print()
result = getrowechelonform(matrix)
print("After Converting to Row Echelon Form:")
print(result)


Matrix Before Converting:
[[ 0 -2  4 -2]
 [ 2  1 10  7]
 [-4  4 -8  4]
 [ 4 -1 14  6]]

After Converting to Row Echelon Form:
[[ 2  1 10  7]
 [ 0 -2  4 -2]
 [ 0  0 20 12]
 [ 0  0  0 -5]]


In [50]:
# RREF

import numpy as np
# Function to check if matrix is in REF
 
def is_row_echelon_form(matrix):
    if not matrix.any():
        return False
 
    rows = matrix.shape[0]
    cols = matrix.shape[1]
    prev_leading_col = -1
 
    for row in range(rows):
        leading_col_found = False
        for col in range(cols):
            if matrix[row, col] != 0:
                if col <= prev_leading_col:
                    return False
                prev_leading_col = col
                leading_col_found = True
                break
        if not leading_col_found and any(matrix[row, col] != 0 for col in range(cols)):
            return False
    return True
 
def find_nonzero_row(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    for row in range(pivot_row, nrows):
        if matrix[row, col] != 0:
            return row
    return None
 
# Swapping rows so that we can have our non zero row on the top of the matrix
def swap_rows(matrix, row1, row2):
    matrix[[row1, row2]] = matrix[[row2, row1]]
 
def make_pivot_one(matrix, pivot_row, col):
    pivot_element = matrix[pivot_row, col]
    matrix[pivot_row] //= pivot_element
#     print(pivot_element)
 
def eliminate_below(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    pivot_element = matrix[pivot_row, col]
    for row in range(pivot_row + 1, nrows):
        factor = matrix[row, col]
        matrix[row] -= factor * matrix[pivot_row]
 
# Implementing above functions
def row_echelon_form(matrix):
    nrows = matrix.shape[0]
    ncols = matrix.shape[1]
    pivot_row = 0
# this will run for number of column times. If matrix has 3 columns this loop will run for 3 times
    for col in range(ncols):
        nonzero_row = find_nonzero_row(matrix, pivot_row, col)
        
        if nonzero_row is not None:
            swap_rows(matrix, pivot_row, nonzero_row)

            make_pivot_one(matrix, pivot_row, col)
            eliminate_below(matrix, pivot_row, col)
            pivot_row += 1
    return matrix
 
 
matrix = np.array([[1,0,8,-4],[0,1,2,12]])
print("Matrix Before Converting:")
print(matrix)
print()
result = row_echelon_form(matrix)
print("After Converting to Row Echelon Form:")
print(result)
if is_row_echelon_form(result):
    print("In REF")
else:
    print("Not in RREF--------------->")



Matrix Before Converting:
[[ 1  0  8 -4]
 [ 0  1  2 12]]

After Converting to Row Echelon Form:
[[ 1  0  8 -4]
 [ 0  1  2 12]]
In REF


In [102]:
# Particular Solution 
B = [42, 8, 0, 0]
nrows = result.shape[0]
ncols = result.shape[1]
print (result)
sum = 0
print()
for j in range(nrows):      
    print (result[:, j] * B[j])

[[ 1  0  8 -4]
 [ 0  1  2 12]]

[42  0]
[0 8]


In [113]:
nrows = result.shape[0]
ncols = result.shape[1]
print (result)
for j in range(ncols):
    print (result[:,j])
#     if (result[:,j] > 1):
#         print (f"non-pivot columns")
#         print (result[:,j])
#     else:
#         print (f"pivot columns")
#         print (result[:,j])
        

[[ 1  0  8 -4]
 [ 0  1  2 12]]
[1 0]
[0 1]
[8 2]
[-4 12]


In [115]:
nrows = result.shape[0]
ncols = result.shape[1]
# print (result)

for i in range(nrows):   
    print ("Pivot Column:")
    for j in range(ncols):
        if result[i,j] in (0, 1):            
            print (result[i,j])
            
for i in range(nrows):   
    print ("Non Pivot Column:")
    for j in range(ncols):
        if result[i,j] not in (0, 1):            
            print (result[i,j])


Pivot Column:
1
0
Pivot Column:
0
1
Non Pivot Column:
8
-4
Non Pivot Column:
2
12


In [ ]:
# sum += result[j][idx] * B[k]
# # print (result.shape)
# # for j in range(nrows):
# #     for idx, val in np.ndenumerate(B):
# #         print (:idx)
# #         sum += sum + result[j][idx] * val

# # print (sum)


else:
            print ("Non-Pivot Columns")
            print (result[i,j])
        

In [70]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [97]:
import numpy as np
a = np.array([[1,12,13,5], [2,4,6,8], [3,6,9,12]])
print (a)
print ()
a[:,np.array([True, True, False, True])]
# >>> a[:,np.array([True, True, False, True])]
# array([[ 1,  2,  4],
#        [ 2,  4,  8],
#        [ 3,  6, 12]])

[[ 1 12 13  5]
 [ 2  4  6  8]
 [ 3  6  9 12]]



array([[ 1, 12,  5],
       [ 2,  4,  8],
       [ 3,  6, 12]])