In [1]:
from sklearn.preprocessing import LabelBinarizer

# Create an instance of LabelBinarizer
label_binarizer = LabelBinarizer()

# Sample labels
labels = ['red', 'blue', 'green', 'red']

# Fit the LabelBinarizer on the labels
label_binarizer.fit(labels)

# Transform the labels into binary vectors
binary_labels = label_binarizer.transform(labels)

print(binary_labels)

[[0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


In [2]:
from sklearn.preprocessing import Binarizer
import numpy as np
#Example numerical data
data = np.array([[1.5, 2.8, 0.9],[0.2, 1.6, 2.7]])

#Binarize data with a threshold of 1.5
binarizer = Binarizer(threshold=1.5)
binary_data = binarizer.transform(data)

print("Original Data:")
print(data)
print("\nBinarized Data:")
print(binary_data)

Original Data:
[[1.5 2.8 0.9]
 [0.2 1.6 2.7]]

Binarized Data:
[[0. 1. 0.]
 [0. 1. 1.]]
