In [2]:
# random is a function, doing random sampling in numpy. 
# Answer to Assignment-2: question 1(i)
# calculate the charateristic polynomial 
# calculate eigen values & eigen vectors
# 

import numpy as np 
from numpy.linalg import eig
from sympy import Matrix 
from sympy.abc import x, y

def transpose(A, rows, cols): 
    B = np.array([[-1 for i in range(cols)] for j in range(rows)])
    for i in range(rows):
        for j in range(cols):
            B[i][j] = A[j][i]
    return B

def multiply_matrices(X, Y):    
    # initialize result matrix
    result = np.array([[-1 for i in range(cols)] for j in range(rows)])

    # iterate through rows of X
    for i in range(len(X)):
       # iterate through columns of Y
       for j in range(len(Y[0])):
           # iterate through rows of Y
           for k in range(len(Y)):
               result[i][j] += X[i][k] * Y[k][j]
    return result

# size of square matrix
size = 3  
rows = cols = size
C = np.random.randint(rows*cols, size=(rows, cols))
CTran = transpose(C, rows, cols)
A1 = multiply_matrices(C, CTran)

# now find the characteristic polynomial of the matrix

M = Matrix(A1)
M.charpoly()
M.charpoly(x) == M.charpoly(y)
M.charpoly(x) == M.charpoly(y)

print(f"The given matrix of random integers 'C':\n{C}") 
print (f"The transpose of C as 'CTran':\n{CTran}")
print (f"The resultant matrix A1 = CTran * C:\n{A1}")
print (f"The characteristic polynomial is: {M.charpoly().as_expr()}=0")
w, v = eig(A1)
print (f"Eigen Values for A1:\n{w}")
print (f"Eigen Vector for A1:\n{v}")



The given matrix of random integers 'C':
[[5 5 8]
 [5 0 4]
 [6 5 8]]
The transpose of C as 'CTran':
[[5 5 6]
 [5 0 5]
 [8 4 8]]
The resultant matrix A1 = CTran * C:
[[113  56 118]
 [ 56  40  61]
 [118  61 124]]
The characteristic polynomial is: lambda**3 - 277*lambda**2 + 2711*lambda - 359=0
Eigen Values for A1:
[2.66845609e+02 1.34264495e-01 1.00201265e+01]
Eigen Vector for A1:
[[-0.64710048 -0.67938669  0.34596922]
 [-0.34285987 -0.14599227 -0.92797272]
 [-0.68096114  0.71911055  0.13846276]]


In [4]:
import numpy as np 
from numpy.linalg import eig
from sympy import Matrix 
from sympy.abc import x, y

def transpose(A, rows, cols): 
    B = np.array([[-1 for i in range(cols)] for j in range(rows)])
    for i in range(rows):
        for j in range(cols):
            B[i][j] = A[j][i]
    return B

def multiply_matrices(X, Y):    
    # initialize result matrix
    result = np.array([[-1 for i in range(cols)] for j in range(rows)])

    # iterate through rows of X
    for i in range(len(X)):
       # iterate through columns of Y
       for j in range(len(Y[0])):
           # iterate through rows of Y
           for k in range(len(Y)):
               result[i][j] += X[i][k] * Y[k][j]
    return result

def calculate_max_eigenvalue(eignvec, A):
    tol = 1e-6
    max_iter = 10
    prev_eignval_max = 0 

    # Iteratively improve the approximations for the largest eigenvalue and eigenvector using the power method 
    for i in range(max_iter): 
        # Compute the updated approximation for the eigenvector 
        eignvec = A @ eignvec / np.linalg.norm(A @ eignvec)
        # Compute the updated approximation for the largest eigenvalue 
        eignval = (eignvec.T @ A @ eignvec) / (eignvec.T @ eignvec)
        print (f"Iteration #{i+1}: Eigen Val = {eignval}")
        # Store the current approximation for the largest eigenvalue 
        prev_eignval_max = eignval
        
    return eignval, eignvec

def compute_x1(eignvec):
    rows, cols = eignvec.shape
    for i in range(rows):
        for j in range(cols):
            x1[i][j] = eignvec[i][j] / pow(eignvec[i][j], 2)
    return x1

# size of square matrix
size = 3  
rows = cols = size
C = np.random.randint(rows*cols, size=(rows, cols))
CTran = transpose(C, rows, cols)
A1 = multiply_matrices(C, CTran)

# now find the characteristic polynomial of the matrix

M = Matrix(A1)
M.charpoly()
M.charpoly(x) == M.charpoly(y)
M.charpoly(x) == M.charpoly(y)

print(f"The given matrix of random integers 'C':\n{C}") 
print (f"The transpose of C as 'CTran':\n{CTran}")
print (f"The resultant matrix A1 = CTran * C:\n{A1}")
print (f"The characteristic polynomial is: {M.charpoly().as_expr()}=0")
w, v = eig(A1)
print (f"Eigen Values for A1:\n{w}")
print (f"Eigen Vector for A1:\n{v}")

# Define the matrix A 
# A = np.array([[1, 3, 7], [3, 2, 5], [7, 5, 4]]) 
A = A1
print (f"A1:\n{A}")
# Choose the initial vector x 
inivec = np.array([[1, 1, 1]]).T 
print (f"Initial e.vector:\n{inivec}")
eignval, eignvec = calculate_max_eigenvalue(inivec, A)
print (f"\nMax eigen value:\n{float(eignval)}")
print (f"\nEigen vector:\n{eignvec}") 
print (f"rows={rows} cols={cols}")
x1 = [[]]
x1 = compute_x1 (eignvec)
print (f"\nx1 = x1 / ||x1||2 :")
for i in range(rows):
    print (x1[i])
print (f"\n Comparing with the Eigen values and E.Vectors with the values from earlier method..")
print (f"\n Eigen Values:\n{eignval}")
print (f"\n Eign Vector:\n{eignvec}")
print (f"\n\n\n\n")

x1 = np.array(x1)
x1T = x1.T
A2 = A1 - (x1@x1T@A1)
print (f"Matrix A1 = \n{A1}")
print (f"Matrix x1 = \n{x1}")
print (f"Matrix x1T = \n {x1T}")
print (f"Matrix A2 = \n {A2}")
E2Val, E2Vec =  calculate_max_eigenvalue(inivec, A2)
print (f"max eigen value:\n{float(E2Val)}")
print (f"eigen vector:\n{E2Vec}") 
print (f"rows={rows} cols={cols}")
x2 = compute_x1 (E2Vec)
print (f"x2 = x2 / ||x2||2 :")
for i in range(rows):
    print (x2[i])
print (f"\n Comparing with the Eigen values and E.Vectors with the values from earlier method..")
print (f"\n Eigen Values:\n{eignval}")
print (f"\n Eign Vector:\n{eignvec}")
print (f"\n\n\n\n")    

# A3 = (A1 − ˆx1ˆxT1A1 − ˆ x2ˆxT2A1)
# A3 = A2 - 
A3 = A2 - x2@x2.T@A1
print (f"Matrix x1 = \n{x2}")
print (f"Matrix x1T = \n {x2.T}")
print (f"A3 =\n{A3}")
E3Val, E3Vec =  calculate_max_eigenvalue(inivec, A3)
print (f"max eigen value:\n{float(E3Val)}")
print (f"eigen vector:\n{E3Vec}") 
print (f"rows={rows} cols={cols}")
x3 = compute_x1 (E3Vec)
print (f"x2 = x2 / ||x2||2 :")
for i in range(rows):
    print (x3[i])
print (f"\n Comparing with the Eigen values and E.Vectors with the values from earlier method..")
print (f"\n Eigen Values:\n{eignval}")
print (f"\n Eign Vector:\n{eignvec}")
print (f"\n\n\n\n")

The given matrix of random integers 'C':
[[0 1 2]
 [5 0 8]
 [4 0 1]]
The transpose of C as 'CTran':
[[0 5 4]
 [1 0 0]
 [2 8 1]]
The resultant matrix A1 = CTran * C:
[[ 4 15  1]
 [15 88 27]
 [ 1 27 16]]
The characteristic polynomial is: lambda**3 - 108*lambda**2 + 869*lambda + 162=0
Eigen Values for A1:
[99.22573779 -0.18228464  8.95654685]
Eigen Vector for A1:
[[-0.15124554 -0.87653408 -0.45696038]
 [-0.93971921  0.27091823 -0.20864111]
 [-0.30667994 -0.39785841  0.86467109]]
A1:
[[ 4 15  1]
 [15 88 27]
 [ 1 27 16]]
Initial e.vector:
[[1]
 [1]
 [1]]
Iteration #1: Eigen Val = [[99.2106467]]
Iteration #2: Eigen Val = [[99.22561623]]
Iteration #3: Eigen Val = [[99.2257368]]
Iteration #4: Eigen Val = [[99.22573779]]
Iteration #5: Eigen Val = [[99.22573779]]
Iteration #6: Eigen Val = [[99.22573779]]
Iteration #7: Eigen Val = [[99.22573779]]
Iteration #8: Eigen Val = [[99.22573779]]
Iteration #9: Eigen Val = [[99.22573779]]
Iteration #10: Eigen Val = [[99.22573779]]

Max eigen value:
99.2257

IndexError: list assignment index out of range