Write a code in your chosen programming language to implement the
Power method and use it to derive the largest eigenvalue λ1 and corresponding
eigenvector x1 of A1. 

Find ˆx1 =
x1
∥x1∥2
. Compare the values
obtained in i) with these values.
Deliverables: The handwritten code that implements the Power method,
the first 10 iterates of eigenvalue generated by the algorithm and the
final λ1 and ˆx1 and a comment on the comparison.

In [91]:
"""
Write a code in your chosen programming language to implement the
Power method and use it to derive the largest eigenvalue λ1 and corresponding
eigenvector x1 of A1. Find ˆx1 = x1 / ∥x1∥2
Compare the values obtained in i) with these values.

Deliverables: The handwritten code that implements the Power method,
the first 10 iterates of eigenvalue generated by the algorithm and the
final λ1 and ˆx1 and a comment on the comparison.

"""
# random is a function, doing random sampling in numpy. 
# Answer to Assignment-2: question 1(i)
# calculate the charateristic polynomial 
# calculate eigen values & eigen vectors
# 

import numpy as np 
from numpy.linalg import eig
from sympy import Matrix 
from sympy.abc import x, y

def transpose(A, rows, cols): 
    B = np.array([[-1 for i in range(cols)] for j in range(rows)])
    for i in range(rows):
        for j in range(cols):
            B[i][j] = A[j][i]
    return B

def multiply_matrices(X, Y):    
    # initialize result matrix
    result = np.array([[-1 for i in range(cols)] for j in range(rows)])

    # iterate through rows of X
    for i in range(len(X)):
       # iterate through columns of Y
       for j in range(len(Y[0])):
           # iterate through rows of Y
           for k in range(len(Y)):
               result[i][j] += X[i][k] * Y[k][j]
    return result

# size of square matrix
# size = 3  
# rows = cols = size
# C = np.random.randint(rows*cols, size=(rows, cols))
# CTran = transpose(C, rows, cols)
# A1 = multiply_matrices(C, CTran)

# A1 = np.array([[1, 1], [1, 1]]) 
A1 = np.array([[1, 3, 7], [3, 2, 5], [7, 5, 4]]) 
w, v = eig(A1)
# now find the characteristic polynomial of the matrix
M = Matrix(A1)
M.charpoly()
M.charpoly(x) == M.charpoly(y)
M.charpoly(x) == M.charpoly(y)
str = M.charpoly().as_expr()


# print(f"The given matrix of random integers 'C':\n{C}") 
# print (f"The transpose of C as 'CTran':\n{CTran}")
print (f"The resultant matrix A1 = CTran * C:\n{A1}")
print (f"Eigen Values for A1:\n{w}")
print (f"Eigen Vector for A1:\n{v}")
print (f"The characteristic polynomial is: {M.charpoly().as_expr()}")
print (f"eigenvalue:{eigenvalue}")
print (f"u={u}")

The resultant matrix A1 = CTran * C:
[[1 3 7]
 [3 2 5]
 [7 5 4]]
Eigen Values for A1:
[12.76668248 -4.80486473 -0.96181775]
Eigen Vector for A1:
[[-0.53632236 -0.71906617  0.44193005]
 [-0.47380736 -0.17680978 -0.86269629]
 [-0.69847327  0.67207302  0.24587181]]
The characteristic polynomial is: lambda**3 - 7*lambda**2 - 69*lambda - 59
eigenvalue:2.0
u=[[-7.88860905e-31]
 [-7.88860905e-31]]


In [1]:
import numpy as np 
from numpy.linalg import eig
from sympy import Matrix 
from sympy.abc import x, y

def transpose(A, rows, cols): 
    B = np.array([[-1 for i in range(cols)] for j in range(rows)])
    for i in range(rows):
        for j in range(cols):
            B[i][j] = A[j][i]
    return B

def multiply_matrices(X, Y):    
    # initialize result matrix
    result = np.array([[-1 for i in range(cols)] for j in range(rows)])

    # iterate through rows of X
    for i in range(len(X)):
       # iterate through columns of Y
       for j in range(len(Y[0])):
           # iterate through rows of Y
           for k in range(len(Y)):
               result[i][j] += X[i][k] * Y[k][j]
    return result

# size of square matrix
size = 3  
rows = cols = size
C = np.random.randint(rows*cols, size=(rows, cols))
CTran = transpose(C, rows, cols)
A1 = multiply_matrices(C, CTran)

# now find the characteristic polynomial of the matrix

M = Matrix(A1)
M.charpoly()
M.charpoly(x) == M.charpoly(y)
M.charpoly(x) == M.charpoly(y)

print(f"The given matrix of random integers 'C':\n{C}") 
print (f"The transpose of C as 'CTran':\n{CTran}")
print (f"The resultant matrix A1 = CTran * C:\n{A1}")
print (f"The characteristic polynomial is: {M.charpoly().as_expr()}=0")
w, v = eig(A1)
print (f"Eigen Values for A1:\n{w}")
print (f"Eigen Vector for A1:\n{v}")

The given matrix of random integers 'C':
[[4 3 3]
 [2 5 0]
 [4 8 0]]
The transpose of C as 'CTran':
[[4 2 4]
 [3 5 8]
 [3 0 0]]
The resultant matrix A1 = CTran * C:
[[33 22 39]
 [22 28 47]
 [39 47 79]]
The characteristic polynomial is: lambda**3 - 140*lambda**2 + 1529*lambda + 73=0
Eigen Values for A1:
[ 1.28055404e+02  1.19921326e+01 -4.75366449e-02]
Eigen Vector for A1:
[[ 0.42608404  0.9017804  -0.07241892]
 [ 0.45970036 -0.28475729 -0.84118302]
 [ 0.77918417 -0.32512366  0.53587931]]


In [11]:
# https://www.geeksforgeeks.org/power-method-determine-largest-eigenvalue-and-eigenvector-in-python/
import numpy as np 
  
def calculate_max_eigenvalue(eignvec, A):
    tol = 1e-6
    max_iter = 10
    prev_eignval_max = 0 

    # Iteratively improve the approximations for the largest eigenvalue and eigenvector using the power method 
    for i in range(max_iter): 
        # Compute the updated approximation for the eigenvector 
        eignvec = A @ eignvec / np.linalg.norm(A @ eignvec)
        # Compute the updated approximation for the largest eigenvalue 
        eignval = (eignvec.T @ A @ eignvec) / (eignvec.T @ eignvec)
        print (f"Iteration #{i+1}: Eigen Val = {eignval}")
        # Store the current approximation for the largest eigenvalue 
        prev_eignval_max = eignval
        
    return eignval, eignvec

def compute_x1(eignvec):
    rows, cols = eignvec.shape
    for i in range(rows):
        for j in range(cols):
            x1[i][j] = eignvec[i][j] / pow(eignvec[i][j], 2)
    return x1


# Define the matrix A 
# A = np.array([[1, 3, 7], [3, 2, 5], [7, 5, 4]]) 
A = A1
print (f"A1:\n{A}")
# Choose the initial vector x 
inivec = np.array([[1, 1, 1]]).T 
print (f"Initial e.vector:\n{inivec}")
eignval, eignvec = calculate_max_eigenvalue(inivec, A)
print (f"Max eigen value:\n{float(eignval)}")
print (f"Eigen vector:\n{eignvec}") 
print (f"Shape of Eigen Vector:- rows={rows} cols={cols}")
# x1 = np.zeros((rows,cols), float)
x1 = np.array(eignvec)
x1 = compute_x1 (eignvec)
print (f"\nx1 = x1 / ||x1||2 :")
for i in range(rows):
    print (x1[i])
print (f"\n Comparing with the Eigen values and E.Vectors with the values from earlier method..")
print (f"Eigen Values:\n{eignval}")
print (f"Eign Vector:\n{eignvec}")
print (f"\n\n\n")
    
x1 = np.array(x1)
x1T = x1.T
A2 = A1 - (x1@x1T@A1)
print (f"Matrix A1 = \n{A1}")
print (f"Matrix x1 = \n{x1}")
print (f"Matrix x1T = \n {x1T}")
print (f"Matrix A2 = \n {A2}")
E2Val, E2Vec =  calculate_max_eigenvalue(inivec, A2)
print (f"Max eigen value:\n{float(E2Val)}")
print (f"Eigen vector:\n{E2Vec}") 
print (f"Shape of Eigen Vector:- rows={rows} cols={cols}")
x2 = compute_x1 (E2Vec)
print (f"x2 = x2 / ||x2||2 :")
for i in range(rows):
    print (x2[i])
print (f"Comparing with the Eigen values and E.Vectors with the values from earlier method..")
print (f"Eigen Values:\n{E2Val}")
print (f"Eigen Vector:\n{E2Vec}")
print (f"\n\n\n")

# A3 = (A1 − ˆx1ˆxT1A1 − ˆ x2ˆxT2A1)
# A3 = A2 - 
A3 = A2 - x2@x2.T@A1
print (f"Matrix x1 = \n{x2}")
print (f"Matrix x1T = \n {x2.T}")
print (f"A3 =\n{A3}")
E3Val, E3Vec =  calculate_max_eigenvalue(inivec, A3)
print (f"Max eigen value:\n{float(E3Val)}")
print (f"Eigen vector:\n{E3Vec}") 
print (f"Shape of Eigen Vector:- rows={rows} cols={cols}")
x3 = compute_x1 (E3Vec)
print (f"x3 = x3 / ||x3||2 :")
for i in range(rows):
    print (x3[i])
print (f"Comparing with the Eigen values and E.Vectors with the values from earlier method..")
print (f"Eigen Values:\n{E3Val}")
print (f"Eigen Vector:\n{E3Vec}")
print (f"\n\n\n")

A1:
[[33 22 39]
 [22 28 47]
 [39 47 79]]
Initial e.vector:
[[1]
 [1]
 [1]]
Iteration #1: Eigen Val = [[128.0241258]]
Iteration #2: Eigen Val = [[128.05512963]]
Iteration #3: Eigen Val = [[128.0554016]]
Iteration #4: Eigen Val = [[128.05540398]]
Iteration #5: Eigen Val = [[128.05540401]]
Iteration #6: Eigen Val = [[128.05540401]]
Iteration #7: Eigen Val = [[128.05540401]]
Iteration #8: Eigen Val = [[128.05540401]]
Iteration #9: Eigen Val = [[128.05540401]]
Iteration #10: Eigen Val = [[128.05540401]]
Max eigen value:
128.05540400556544
Eigen vector:
[[0.42608404]
 [0.45970036]
 [0.77918417]]
Shape of Eigen Vector:- rows=3 cols=3

x1 = x1 / ||x1||2 :
[2.34695484]
[2.17533005]
[1.28339363]

 Comparing with the Eigen values and E.Vectors with the values from earlier method..
Eigen Values:
[[128.05540401]]
Eign Vector:
[[0.42608404]
 [0.45970036]
 [0.77918417]]




Matrix A1 = 
[[33 22 39]
 [22 28 47]
 [39 47 79]]
Matrix x1 = 
[[2.34695484]
 [2.17533005]
 [1.28339363]]
Matrix x1T = 
 [[2.346

In [95]:
"""
Write a code to construct matrix A2 = (A1− ˆx1ˆxT1
A1). Use the Power
method code written in ii) and use it to derive the largest eigenvalue
λ2 and corresponding eigenvector x2 of A2. Find ˆx2 = x2 / ∥x2∥2
. Compare the values obtained in i) with these values.

Deliverables: The first 10 iterates of λ2 and ˆx2 and a comment on the
comparison.
"""

x1 = np.array(x1)
x1T = x1.T
A2 = A1 - (x1@x1T@A1)

print (f"Matrix A1 = \n{A1}")
print (f"Matrix x1 = \n{x1}")
print (f"Matrix x1T = \n {x1T}")
print (f"Matrix A2 = \n {A2}")




Matrix A1 = 
[[1 3 7]
 [3 2 5]
 [7 5 4]]
Matrix x1 = 
[[1.86453158]
 [2.11055651]
 [1.43170431]]
Matrix x1T = 
 [[1.86453158 2.11055651 1.43170431]]
Matrix A2 = 
 [[-32.96828116 -28.64712214 -47.68917417]
 [-35.45039554 -33.82295961 -56.90541018]
 [-19.08297704 -19.30064554 -37.99377847]]
