In [ ]:
# Program to multiply two matrices using nested loops

def multiply_matrix(X, Y):
    
    # result is 3x4
    result = np.array([[0,0,0,0],
             [0,0,0,0],
             [0,0,0,0]])

    # iterate through rows of X
    for i in range(len(X)):
       # iterate through columns of Y
       for j in range(len(Y[0])):
           # iterate through rows of Y
           for k in range(len(Y)):
               result[i][j] += X[i][k] * Y[k][j]
    return result

# 3x3 matrix
X = np.array([[12,7,3],
    [4 ,5,6],
    [7 ,8,9]])

# 3x4 matrix
Y = np.array([[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]])

result = multiply_matrix(X, Y)
for r in result:
   print(r)

"""
[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]
"""

In [ ]:
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
 
# result will be 3x4
result = [[sum(a * b for a, b in zip(A_row, B_col)) 
                        for B_col in zip(*B)]
                                for A_row in A]
 
for r in result:
    print(r)

In [ ]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

In [ ]:
# determinant of a matrix 

# Python program to find Determinant of a matrix
 
 
def determinantOfMatrix(mat, n):
 
    temp = [0]*n  # temporary array for storing row
    total = 1
    det = 1  # initialize result
 
    # loop for traversing the diagonal elements
    for i in range(0, n):
        index = i  # initialize the index
 
        # finding the index which has non zero value
        while(index < n and mat[index][i] == 0):
            index += 1
 
        if(index == n):  # if there is non zero element
            # the determinant of matrix as zero
            continue
 
        if(index != i):
            # loop for swapping the diagonal element row and index row
            for j in range(0, n):
                mat[index][j], mat[i][j] = mat[i][j], mat[index][j]
 
            # determinant sign changes when we shift rows
            # go through determinant properties
            det = det*int(pow(-1, index-i))
 
        # storing the values of diagonal row elements
        for j in range(0, n):
            temp[j] = mat[i][j]
 
        # traversing every row below the diagonal element
        for j in range(i+1, n):
            num1 = temp[i]     # value of diagonal element
            num2 = mat[j][i]   # value of next row element
 
            # traversing every column of row
            # and multiplying to every row
            for k in range(0, n):
                # multiplying to make the diagonal
                # element and next row element equal
 
                mat[j][k] = (num1*mat[j][k]) - (num2*temp[k])
 
            total = total * num1  # Det(kA)=kDet(A);
 
    # multiplying the diagonal elements to get determinant
    for i in range(0, n):
        det = det*mat[i][i]
 
    return int(det/total)  # Det(kA)/k=Det(A);
 
 
# Drivers code
if __name__ == "__main__":
    # mat=[[6 1 1][4 -2 5][2 8 7]]
 
    mat = [[1, 0, 2, -1], [3, 0, 0, 5], [2, 1, 4, -3], [1, 0, 5, 0]]
    N = len(mat)
     
    # Function call
    print("Determinant of the matrix is : ", determinantOfMatrix(mat, N))
    

In [ ]:
# importing the numpy package
# as np
import numpy as np
 
def determinant(mat):
     
    # calling the det() method
    det = np.linalg.det(mat)
    return round(det)
 
# Driver Code
# declaring the matrix
mat = [[1, 0, 2, -1],
       [3, 0, 0, 5],
       [2, 1, 4, -3],
       [1, 0, 5, 0]]
 
# Function call
print('Determinant of the matrix is:',
      determinant(mat))

In [1]:
# https://www.geeksforgeeks.org/eigen-values/
# https://www.geeksforgeeks.org/find-characteristic-polynomial-of-a-square-matrix/
# The characteristic polynomial of the 3×3 matrix can be calculated using the formula 
# x3 – (Trace of matrix)*x2 + (Sum of minors along diagonal)*x – determinant of matrix = 0

N = 3
 
# Trace
def findTrace(mat, n):
    sum = 0
    for i in range(n):
        sum += mat[i][i]
    return sum
 
# Sum of minors along diagonal
def sum_of_minors(mat, n):
    return ((mat[2][2] * mat[1][1] - mat[2][1] * mat[1][2])
    + (mat[2][2] * mat[0][0] - mat[2][0] * mat[0][2])
    + (mat[1][1] * mat[0][0] - mat[1][0] * mat[0][1]))
 
# Function to get cofactor of mat[p][q]
# in temp[][]. n is current dimension of mat[][]
# Cofactor will be used for calculating determinant
def getCofactor(mat, temp, p, q, n):
    i,j = 0,0
 
    # Looping for each element of the matrix
    for row in range(n):
        for col in range(n):
 
            # Copying into temporary matrix only those
            # element which are not in given row and
            # column
            if (row != p and col != q):
                    temp[i][j] = mat[row][col]
                    j += 1
 
                    # Row is filled, so increase row index
                    # and reset col index
                    if (j == n - 1):
                        j = 0
                        i += 1
 
# Function for calculating
# determinant of matrix
def determinantOfMatrix(mat, n):
 
    # Initialize result
    D = 0
 
    # Base case : if matrix
    # contains single element
    if (n == 1):
        return mat[0][0]
 
    # To store cofactors
    temp = [[0 for i in range(n)] for j in range(n)]
 
    # To store sign multiplier
    sign = 1
 
    # Iterate for each element of first row
    for f in range(n):
 
        # Getting Cofactor of mat[0][f]
        getCofactor(mat, temp, 0, f, n)
        D += sign * mat[0][f] * determinantOfMatrix(temp, n - 1)
 
        # Terms are to be added with alternate sign
        sign = -sign
 
    return D
 
# Driver Code
 
# Given matrix
mat = [[0, 1, 2], [1, 0, -1], [2, -1, 0]]
trace = findTrace(mat, 3)
s_o_m = sum_of_minors(mat, 3)
det = determinantOfMatrix(mat, 3)
 
print("x^3",end="")
if (trace != 0):
    print(f" {trace * -1}x^2",end="") if(trace < 0) else print(f" - {trace}x^2",end="")
 
if (s_o_m != 0):
    print(f" - {s_o_m * -1}x",end="") if(s_o_m < 0) else print(f" + {s_o_m}x",end="")
 
if (det != 0):
    print(f" + {det * -1}",end="") if (det < 0) else print(f" -  {det}",end="")

x^3 - 6x + 4

In [1]:
# Char poly 

from sympy import Matrix
from sympy.abc import x, y
M = Matrix([[1, 1], [1, 1]])
M.charpoly()
M.charpoly(x) == M.charpoly(y)
M.charpoly(x) == M.charpoly(y)
M.charpoly().as_expr()

lambda**2 - 2*lambda

In [2]:
import numpy as np 

# To generate a matrix of random integers 
C = np.random.rand(3, 4)
print (C)

# D = np.random.randint(low=0, high=None, size=None, dtype='l')
D = np.random.randn(3, 4)
print (D)


[[0.38440378 0.53157312 0.4750997  0.85885793]
 [0.12090622 0.35262994 0.15291918 0.35829428]
 [0.55083692 0.51358559 0.81157313 0.42113603]]
[[-0.46341395  0.31977805  1.32357767  0.5445828 ]
 [-0.59141034 -0.61104756 -1.20329616 -0.35206001]
 [ 0.9461938  -0.13927154  0.08186411  1.29949078]]


In [ ]:
shape = (3, 4)
arr = np.zeros(shape)
print (arr)



a = list([[]*3]*3)
print (a)

b = [[] for _ in range(3)]
print (b)

c = [[]]
print (c)

my_list = [[None for j in range(columns)] for i in range(rows)]
print (my_list)


rows, columns = 3, 4
matrix = a = np.random.randint(10, size=(2,3))
print (matrix)

In [ ]:
def findTrace(mat, n): 
 
    sum = 0; 
    for i in range(n): 
        sum += mat[i][i]; 
    return sum; 
# Driver Code 
mat = [[1, 1, 1, 1, 1], 
       [2, 2, 2, 2, 2], 
       [3, 3, 3, 3, 3], 
       [4, 4, 4, 4, 4], 
       [5, 5, 5, 5, 5]]; 
 
print("Trace of Matrix =", findTrace(mat, 5)); 

In [ ]:
# Char poly 

from sympy import Matrix
from sympy.abc import x, y
M = Matrix([[1, 1], [1, 1]])
M.charpoly()
M.charpoly(x) == M.charpoly(y)
M.charpoly(x) == M.charpoly(y)
M.charpoly().as_expr()

In [ ]:
# https://pythonnumericalmethods.berkeley.edu/notebooks/chapter15.04-Eigenvalues-and-Eigenvectors-in-Python.html
# https://math.stackexchange.com/questions/2063913/power-method-eigenvalues

import numpy as np
from numpy import linalg as LA

A = np.matrix([[0,11,-5] , [-2,17,-7] , [-4,26,-10]])
X0 = np.matrix([1,1,1]).T
iterations = 3

for i in range (iterations):
    A = A*A

x = A*X0
norm = LA.norm(x)
print x/norm
print LA.eig(A)[1]

In [ ]:
import numpy as np 
  
# Define the matrix A 
# A = np.array([[2, 1], [1, 2]]) 
A = np.array([[1, 3, 7], [3, 2, 5], [7, 5, 4]])   
# Choose the initial vector x 
x = np.array([[1, 1, 1]]).T 
  
# Define the tolerance for the eigenvalue 
# and eigenvector approximations 
# (i.e. the maximum allowed difference between 
# the approximations and the actual values) 
tol = 1e-6
  
# Define the maximum number of iterations 
max_iter = 100
  
# Define the variable lam_prev to store the 
# previous approximation for the largest eigenvalue 
lam_prev = 0
  
# Iteratively improve the approximations 
# for the largest eigenvalue and eigenvector 
# using the power method 
for i in range(max_iter): 
    # Compute the updated approximation for the eigenvector 
    x = A @ x / np.linalg.norm(A @ x) 
  
    # Compute the updated approximation for the largest eigenvalue 
    lam = (x.T @ A @ x) / (x.T @ x) 
  
    # Check if the approximations have converged 
    if np.abs(lam - lam_prev) < tol: 
        break
  
    # Store the current approximation for the largest eigenvalue 
    lam_prev = lam 
  
# Print the approximations for the 
# largest eigenvalue and eigenvector 
print(float(lam)) 
print(x) 