In [ ]:
## Multiplication of matrices 
    - To multiply two matrices A of order mxn and B or order pxq
    - the number of columns of A must be equal to no. of rows of B i.e. n = p 
    
## Transposition of Matrix 

## Symmetric Matrices 
A (ij) = A (ji)  

## Skew-symmetric Matrix
A ij = a Aji 

## Triangular Matrix 
    Upper triangular if A ij = 0 for all i>j
    
    Lower Triangular if A ij = 0 for all i<j
    
Diagonal Matrix 
    A(ij) for all i != j  

Sparse Matrix 
    Many zero and few non-zero entities.
    
    

In [1]:
# A basic code for matrix input from user

R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))

# Initialize matrix
matrix = []
print("Enter the entries rowwise:")

# For user input
for i in range(R): # A for loop for row entries
    a =[]
    for j in range(C): # A for loop for column entries
        a.append(int(input()))
    matrix.append(a)

# For printing the matrix
for i in range(R):
    for j in range(C):
        print(matrix[i][j], end = " ")
    print()

Enter the number of rows:3
Enter the number of columns:3
Enter the entries rowwise:
1
3
4
5
6
7
1
1
1
1 3 4 
5 6 7 
1 1 1 


2 3 4 
5 6 7 
8 0 -11 
KRP (i,j) = (1, 0) entity value is 1.0
KRP (i,j) = (1, 1) entity value is 1.0
KRP (i,j) = (1, 2) entity value is 1.0
KRP (i,j) = (2, 0) entity value is 1.0
KRP (i,j) = (2, 2) entity value is 1.0
2 3 4 
1.0 1.0 1.0 
1.0 0 1.0 


In [ ]:
1. Check if the first element of the matrix is zero 
2. If Yes, then Go TO 
3. Else, Next step
4. Skip row and go to next row
5. If 1st element is non-zero, then divide the row by the value of first element (this will make leading element of the row 
                                                                                  equal to 1) 
6. 

In [ ]:


Elementary Row operations 

1. Interchange two rows 

2. Addition of a constant multiple of one row to another row 

3. Multiplication of a row by a non-zero constant 

Note: These operations are for rows, not for columns!
    
Row Echelon Form (REF)
    1. Any rows of all rows zeros are below any other non-zero rows 
    2. Each leading entry of row is in a column to the right of the leading entry of the row above it
    3. All entries in a column below a leading entry are zeroes
    
Reduced Row Echelon Form 
    A matrix is in a Row reduced echelon form if it is in echelon form and additionally..
        1. The leading entry in each row is 1
        2. Each leading 1 is the only non-zero entity in its column 
        

In [28]:
import numpy as np

"""
Function: Reduces the matrix row by row until Row Echelon Form achieved
Input: 4 X 4 Matrix
Output: RREF Form of Matrix, if not possible, returns Singularity Test value.
"""
def rowReduce(A) :
    B = np.array(A, dtype=np.float_) # Taking B as a copy of A, because we are going to alter it's values.
    try:
        reduceRowZero(B)
        reduceRowOne(B)
        reduceRowTwo(B)
        reduceRowThree(B)
    except MatrixIsSingular:
        return print("Singular Matrix")
    return B

# Error flag, when the matrix is singular.
class MatrixIsSingular(Exception): pass

"""
Function: Tests if the first element of Row Zero is 0, if 0 then add lower rows until we can make it non-zero.
          If we fail to make it non-zero, matrix is singular. If we succeed to make it non-zero or i is already
          non-zero, we simply divide the whole row by the first element. This gives us first element, as needed, = 1.
Input: 4 X 4 Matrix
Output: First Row into RREF
"""
def reduceRowZero(A) :
    if A[0,0] == 0 :
        A[0] = A[0] + A[1]
    if A[0,0] == 0 :
        A[0] = A[0] + A[2]
    if A[0,0] == 0 :
        A[0] = A[0] + A[3]
    if A[0,0] == 0 :
        raise MatrixIsSingular()
    # diagonal element as one 
    A[0] = A[0] / A[0,0]
    return A

"""
Function: For each row further, first, we will set the sub-diagonal elements to zero.
          Then, make the diagonal element = 1. Repeating the setting as we did above.
Input: 4 X 4 Matrix, with Row Zero in RREF
Output: 4 X 4 Matrix, with Row Zero and Row One in RREF
"""
def reduceRowOne(A) :
    A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        raise MatrixIsSingular()
    # set the diagonal element = 1, by dividing the whole row by that element.
    A[1] = A[1] / A[1,1]
    return A

def reduceRowTwo(A) :
    # set the sub-diagonal elements of row two to zero 
    A[2] = A[2] - A[2,0] * A[0]
    A[2] = A[2] - A[2,1] * A[1]
    
    # Next, test that the diagonal element is not zero.
    if A[2,2] == 0 :
        # adds a lower row to row 2.
        A[2] = A[2] + A[3]
        # again set the sub-diagonal elements to zero.
        A[2] = A[2] - A[2,0] * A[0]
        A[2] = A[2] - A[2,1] * A[1]
    if A[2,2] == 0 :
        raise MatrixIsSingular()
    # set the diagonal element = 1, by dividing the whole row by that element.
    A[2] = A[2] / A[2,2]
    return A

def reduceRowThree(A) :
    # set the sub-diagonal elements of row three to zero.
    A[3] = A[3] - A[3,0] * A[0]
    A[3] = A[3] - A[3,1] * A[1]
    A[3] = A[3] - A[3,2] * A[2]
    # test if the diagonal element is zero.
    if A[3,3] == 0:
        raise MatrixIsSingular()
    # Transform the row to set the diagonal element = 1.
    A[3] = A[3] / A[3,3]
    return A


#### Test Cases ####

# A = np.array([
#         [2, 0, 0, 0],
#         [0, 3, 0, 0],
#         [0, 0, 4, 4],
#         [0, 0, 5, 5]
#     ], dtype=np.float_)

# rowReduce(A) #Singular Matrix

A = np.array([
        [0, 7, -5, 3],
        [2, 8, 0, 4],
        [3, 12, 0, 5],
        [1, 3, 1, 3]
    ], dtype=np.float_)

rowReduce(A) #Non-singular Matrix

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [32]:
import numpy as np
NEARZERO = 1.0e-10

A = np.array( [ [11,2,3], [4,5,6], [7,0,9] ], dtype="float" )
# A = [[2,3,4],[5,6,7],[8,0,-11]]
print( "Input matrix:\n", A )

N = len( A )

pivotRow = 0
for column in range( N ):

    # Partial pivot: swap rows if necessary to put the largest absolute element in this column into the pivot row
    bestRow = pivotRow
    for row in range( pivotRow + 1, N ):                                       # find largest in this column
        if ( abs( A[row,column] ) > abs( A[bestRow,column] ) ): bestRow = row
    if bestRow != pivotRow:                                                    # swap rows
        temp = A[pivotRow,column:]
        A[pivotRow,column:] = A[bestRow,column:]
        A[bestRow ,column:] = temp

    # Now subtract the appropriate multiples of the pivot row from lower rows (like Gaussian elimination)
    if abs( A[pivotRow,column] ) > NEARZERO:                                   # provided we have a non-zero pivot
        A[pivotRow,column:] = A[pivotRow,column:] / A[pivotRow,column]         # make the pivot entry 1
        for row in range( pivotRow + 1, N ):
            A[row,column:] -= A[row,column] * A[pivotRow,column:]
            A[row,column] = 0.0                                                # avoid round-off errors
        pivotRow += 1

print( "\nOutput matrix:\n", A )
print( "\nRank = ", pivotRow )
if pivotRow < N: print( "Matrix is singular" )

Input matrix:
 [[11.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  0.  9.]]

Output matrix:
 [[1.         0.18181818 0.27272727]
 [0.         1.         1.14893617]
 [0.         0.         1.        ]]

Rank =  3
